name: Linting for push and PR
on: [push, pull_request]
jobs:
  check-internal-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build website
        run: bundle exec jekyll build --strict_front_matter
      - name: Validate HTML and check links
        run: |
          bundle exec htmlproofer \
            --assume-extension \
            --allow-hash-href \
            --ignore_empty_alt \
            --disable-external \
            --ignore_status_codes 405,429,503,999 \
            --allow_missing_href  \
            --enforce-https=false  \
            --check-internal-hash=false  \
            ./_site
