name: Deploy Preview for Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true

    - name: Install dependencies
      run: |
        bundle install

    - name: Build Jekyll site
      run: |
        bundle exec jekyll build --destination _site

    - name: Deploy to GitHub Pages for preview
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        cname: ''

    - name: Comment with preview URL
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PREVIEW_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.pull_request.number }}"
        COMMENT_BODY="🎉 A preview of this PR is available at: [${PREVIEW_URL}](${PREVIEW_URL})"
        gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT_BODY"
